name: Simple Math CI

on:
  workflow_dispatch:
   inputs:
      test_1:
        description: "The name to say hello to"
        required: true
        default: "1"
      test_2:
        description: "The name to say hello to"
        required: true
        default: "1"
      push:
        branches: 
         - main

env: 
  test_1: ${{ inputs.test_1 }}
  test_2: "10"

jobs:
  say-hello:
    runs-on: ubuntu-latest
   
    steps:
      - name: Step 1 - Say hello
        run: 
          result=$(($test_1 + $test_2))
          echo "Result: $result"